### PR TITLE
Upgrade component to legacy mode

### PR DESCRIPTION
**Pull request by rgreinho**
Update this component as per the upgrade guide:
* Update bower dependencies
* Update DOM template
* Update event functions
* Minor fixes

### CODE REVIEW

**Comment by rgreinho** [comment]
I'll rebase everything later.

**Comment by masonlouchart** [comment]
I think it can be closed due to the rebase, isn't it?

**Comment by rgreinho** [comment]
To clarify, this PR was for the legacy mode. What you call the rebase is for Polymer 2.x.

**Comment by masonlouchart** [comment]
Whaaaaat....I lost my mind yesterday. Sorry about my nonsense comments. 😖

**Pull request merged**
